[Unit]
Before=sysroot.mount
Wants=sysroot.mount

[Service]
ExecStart=
ExecStart=/usr/bin/systemd-cryptsetup attach 'root' '/dev/gpt-auto-root-luks' '' 'tpm2-device=auto,tpm2-measure-pcr=yes,tries=0'
ExecStartPost=/usr/bin/initrd-fsck-root.sh
