[Content]
RemoveFiles=
    /usr/lib/systemd/system-generators/systemd-getty-generator
    /usr/lib/systemd/system/multi-user.target.wants/getty.target
    /usr/lib/systemd/system/console-getty.service
    /usr/lib/systemd/system/container-getty@.service
    /usr/lib/systemd/system/debug-shell.service
    /usr/lib/systemd/system/getty-static.service
    /usr/lib/systemd/system/getty@.service
    /usr/lib/systemd/system/serial-getty@.service
