[Content]
RemoveFiles=
    /usr/bin/chage
    /usr/bin/chfn
    /usr/bin/chsh
    /usr/bin/expiry
    /usr/bin/gpasswd
    /usr/bin/passwd
    /usr/bin/su
    /usr/lib/polkit-1/polkit-agent-helper-1
    /usr/sbin/unix_chkpwd
