version: "2"
linters:
  default: all
  disable:
    - cyclop # handled by revive
    - depguard
    - err113
    - exhaustruct
    - funlen # handled by revive
    - gochecknoglobals
    - gocognit
    - gocyclo
    - ireturn
    - lll
    - maintidx
    - mnd
    - testpackage
    - unparam
    - varnamelen
    - wrapcheck
    - wsl

  settings:
    gosec:
      config:
        G301: "0755"
        G306: "0644"

    nestif:
      min-complexity: 8

    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: cognitive-complexity
          arguments:
            - 100
        - name: cyclomatic
          arguments:
            - 50
        - name: flag-parameter
          disabled: true
        - name: function-length
          arguments:
            - 150
            - 200
        - name: line-length-limit
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: nested-structs
          disabled: true

    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake

  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        source: ^\s*defer\s+

    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/lxc/incus-os/incus-osd)

    goimports:
      local-prefixes:
        - github.com/lxc/incus-os/incus-osd

  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
