# Records are collected by systemd-journald, auditd only consumes them.
local_events = yes
write_logs = no
log_file = /run/audit/audit.log
log_format = ENRICHED
flush = NONE
plugin_dir = /run/audit/plugins.d
space_left = 75
space_left_action = IGNORE
admin_space_left = 50
admin_space_left_action = IGNORE
disk_full_action = IGNORE
disk_error_action = IGNORE
use_libwrap = no
