#!/bin/sh -eu
if [ -z "${1:-}" ]; then
    echo "Usage: ${0} NAME"
    exit 1
fi

# Check if instance already exists
if incus info "${1}" >/dev/null 2>&1; then
    echo "Instance ${1} already exists"
    exit 1
fi

# Get the OS name
OSNAME=$(grep "ImageId=" mkosi.conf | cut -d '=' -f 2)

# Setup temporary directory
cleanup() {
    rm -f "${OSNAME}_*.iso"
}
trap cleanup EXIT HUP INT TERM

# Grab and configure the image
incus-osd/flasher-tool --seed test/seed.install.tar --format iso
# shellcheck disable=SC2010
IMG_NAME=$(ls "${OSNAME}"_*.iso | grep -v usr | grep -v esp | sort | tail -1)

# Create an instance
echo "=> Creating an ${OSNAME} instance"
incus create --vm --empty "${1}" \
    -c security.secureboot=false \
    -c limits.cpu=4 \
    -c limits.memory=8GiB \
    -d root,size=50GiB
incus config device add "${1}" vtpm tpm
incus config device add "${1}" boot-media disk source="$(pwd)/${IMG_NAME}" boot.priority=10

echo "=> Starting ${OSNAME} for installation"
incus start "${1}" --console
sleep 5
incus console "${1}"
sleep 5
clear

# Remove install media
incus stop -f "${1}"
incus config device remove "${1}" boot-media

# Start the installed system
echo "=> Starting installed ${OSNAME}"
incus start "${1}" --console
