[Config]
Dependencies=base

[Output]
Format=sysext
Overlay=yes
ManifestFormat=json
ImageVersion=

[Content]
BaseTrees=%O/base
PostInstallationScripts=../base/mkosi.postinst.d/10-strip-privileges.sh.chroot
Packages=
    mtools
    xz-utils
