# IncusOS-specific note: the profile ID must match the value for `incusos.profile=` that's
# appended to the kernel's command line. This is used by IncusOS to properly identify
# which UKI profile has booted.

[UKIProfile]
Profile=
    ID=hwinfo
    TITLE=Display hardware info

Cmdline=
    incusos.profile=hwinfo
