name: Certificate tests
on:
  schedule:
  - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  certificate-e2e-tests:
    name: IncusOS Certificate end-to-end tests
    strategy:
      fail-fast: false
    timeout-minutes: 120
    runs-on:
      - self-hosted
      - arch-amd64
      - lxc-incusos-daily
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26.x

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get install --yes \
            linux-headers-$(uname -r)
          sudo --preserve-env=DEBIAN_FRONTEND apt-get install --yes \
            binutils \
            curl \
            debian-archive-keyring \
            devscripts \
            dosfstools \
            efitools \
            gdisk \
            genisoimage \
            libnbd-dev \
            make \
            mtools \
            openssl \
            parted \
            pkgconf \
            pipx \
            qemu-utils \
            zfsutils-linux \
            zip

      - name: Setup mkosi
        run: |
          pipx install git+https://github.com/systemd/mkosi.git@v25.3

      - name: Setup Incus
        run: |
          curl https://pkgs.zabbly.com/get/incus-daily | sudo sh
          sudo chmod 666 /var/lib/incus/unix.socket

          echo "initializing incus with zfs backend and 200MB loop device"
          incus admin init --auto --storage-backend=zfs --storage-create-loop=200

          echo "setting zfs sync to disabled for better performance in CI environment"
          sudo zfs set sync=disabled default

      - name: Build local test images
        run: |
          export PATH="${PATH}:/${HOME}/.local/bin"

          rm -rf certs/ incus-osd/certs/files/
          make generate-test-certs

          make

          make publish-local-update

          export VERSION=$(ls local-image-server/ | grep ^202)
          SIG_KEY=./certs/update-E1.key SIG_CERTIFICATE=./certs/update-E1.crt SIG_CHAIN=./incus-osd/certs/files/update-E1.crt ./incus-osd/image-publisher promote ./local-image-server/ ${VERSION} stable

          # Perform a second build with a different Secure Boot signing key.
          # We don't automatically promote it to stable so we can control
          # when the test VM is upgraded.
          make clean
          ./scripts/test/switch-secure-boot-signing-key.sh 2
          make

          make publish-local-update

          # Generate a dbx update for the Secure Boot certificate used by the first build
          export FINGERPRINT=$(openssl x509 -in "incus-osd/certs/files/secureboot-DB-1-R1.crt" -noout -fingerprint -sha256 | cut -d '=' -f2 | tr -d ':')
          cert-to-efi-sig-list -g "433f8160-9ab6-4407-8e38-12d70e1d54e5" "incus-osd/certs/files/secureboot-DB-1-R1.crt" "dbx_${FINGERPRINT}.esl"
          sign-efi-sig-list -g "433f8160-9ab6-4407-8e38-12d70e1d54e5" -a -c "incus-osd/certs/files/secureboot-KEK-R1.crt" -k "certs/secureboot-KEK-R1.key" dbx "dbx_${FINGERPRINT}.esl" "dbx_${FINGERPRINT}.auth"

          (cd ./certs/efi/updates/ && tar cf ../../../sb-update.tar *.auth)
          tar cf sb-uki-revoke.tar *.auth

      - name: Run certificate end-to-end tests
        run: |
          export SERVER_IP=$(incus network list incusbr0 -c 4 -f csv | cut -d '/' -f 1)
          export IMAGES_SERVER="http://${SERVER_IP}:8123"

          make start-local-image-server

          ./incus-osd/tests/certificate-e2e-tests.py
