name: Commits
on:
  - pull_request

permissions:
  contents: read

jobs:
  dco-check:
    permissions:
      pull-requests: read  # for KineticCafe/actions-dco to get list of commits from the PR
    name: Signed-off-by (DCO)
    runs-on: ubuntu-24.04
    steps:
    - uses: KineticCafe/actions-dco@v3.1.0

  target-branch:
    permissions:
      contents: none
    name: Branch target
    runs-on: ubuntu-24.04
    steps:
    - name: Check branch target
      env:
        TARGET: ${{ github.event.pull_request.base.ref }}
      run: |
        set -x
        [ "${TARGET}" = "main" ] && exit 0

        echo "Invalid branch target: ${TARGET}"
        exit 1
