name: Daily
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  api-tests:
    name: IncusOS API tests
    strategy:
      fail-fast: false
    timeout-minutes: 600
    runs-on:
      - self-hosted
      - arch-amd64
      - lxc-incusos-daily
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26.x

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo --preserve-env=DEBIAN_FRONTEND apt-get install --yes \
            curl \
            dosfstools \
            gdisk \
            genisoimage \
            mtools \
            openssl \
            python3-requests

      - name: Setup Incus
        run: |
          curl https://pkgs.zabbly.com/get/incus-daily | sudo sh
          sudo chmod 666 /var/lib/incus/unix.socket

          echo "initializing incus with dir backend"
          incus admin init --auto --storage-backend=dir

      - name: Run API tests
        run: |
          incus-osd/tests/api-tests.py
