name: Daily
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  api-tests:
    name: IncusOS API tests
    strategy:
      fail-fast: false
    timeout-minutes: 600
    runs-on:
      - self-hosted
      - cpu-24
      - mem-48G
      - disk-250G
      - arch-amd64
      - image-debian-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get install --yes \
            linux-headers-$(uname -r)
          sudo apt-get install --yes \
            dosfstools \
            gdisk \
            genisoimage \
            mtools \
            zfsutils-linux

      - name: Setup Incus
        run: |
          curl https://pkgs.zabbly.com/get/incus-daily | sudo sh
          sudo chmod 666 /var/lib/incus/unix.socket
          echo "initializing incus with zfs backend and 200MB loop device"
          incus admin init --auto --storage-backend=zfs --storage-create-loop=200
          echo "setting zfs sync to disabled for better performance in CI environment"
          zfs set sync=disabled default

      - name: Run API tests
        run: |
          incus-osd/tests/api-tests.py
